version: '3'

tasks:
  default:
    - task: build:rpmspec
  build:distrobox:
    desc: Generate a distrobox container with necessary dependencies to build this repo's RPM files.
    cmds:
      - distrobox assemble create -f {{.BUILDER_INI}}
    vars:
      BUILDER_INI: ./builder.distrobox.ini
  build:rpmspec:
    desc: Build a specified RPKG rpm spec in the CLI arguments.
    cmds:
      - rpkg -v -C ./rpkg.conf local --outdir "{{.OUT}}" {{.CLI_ARGS}}
    vars:
      OUT: output
