version: '3'

tasks:
  default:
    cmds:
      - task: build:rpmspec
  build:rpmspec:
    cmds:
      - mkdir -p ./output
      - podman build -v "$(realpath "$PWD")/output:/output:Z" -f Containerfile .
